modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = ""
license = "LGPL-3.0-only"

[[mods]]
modId = "wood_you_dye"
version = "${version}"
displayName = "Wood You Dye"
displayURL = ""
authors = [
    "Siuolplex"
]
description = '''
A Mod thats all about dyable wooden planks!
'''
logoFile = "icon.png"

[[dependencies.wood_you_dye]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wood_you_dye]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
